# Example configuration for reconciling Oracle to SQL Server tables
debug: high
source:
  type: oracle
  env:
    user: ORACLE_USER
    password: ORACLE_PASSWORD
    host: ORACLE_HOST
    port: ORACLE_PORT
    service: ORACLE_SERVICE
  schema: source_schema_name  # environment-specific name
  table: source_table_name  # environment-specific name
  columns:
    - id
    - year
    - month
    - data_column_1
    - data_column_2

destination:
  type: sqlserver
  env:
    driver: SQLSERVER_DRIVER
    server: SQLSERVER_SERVER
    database: SQLSERVER_DATABASE
    trusted_connection: SQLSERVER_TRUSTED
    trust_server_certificate: SQLSERVER_TRUST_SERVER_CERT
  schema: destination_schema_name  # environment-specific name
  table: destination_table_name  # environment-specific name

primary_key: id

comparison:
  use_row_hash: true
  parallel: true
  parallel_mode: batch
  include_nulls: true
  workers: auto

partitioning:
  year_column: year
  month_column: month
  week_column: week
  scope:
    - { year: '2024', month: '05', weeks: [1, 2, 3, 4] }
    - { year: '2024', month: '06', weeks: [1, 2, 3, 4, 5] }
    - { year: '2023', month: '12' }  # fallback to month-only

output:
  format: table
  schema: recon
  table: discrepancies

updates:
  dry_run: true
  skip_nulls: true
